<?php 
error_reporting(E_ERROR | E_WARNING | E_PARSE);

/*
Michelle Knight's Drop Calc - Version 3
Author - Michelle Knight
Copyright 2006
Contact - dropcalc@msknight.com

GNU General Licence
Use and distribute freely, but leave headers intact and make no charge.
Change HTML code as necessary to fit your own site.
Code distributed without warantee or liability as to merchantability as
no charge is made for its use.  Use is at users risk.
*/


//
// ***** EXECUTION STARTS HERE *****
//

include('config.php');
include('config-read.php');
include('skin.php');
include('common.php');

$langval = input_check($_REQUEST['langval'],2);

// Retrieve environment variables
wrap_start_dummy($username, $token, $_GET, $_POST, $langval, $default_lang, $language_array, $db_location, $db_user, $db_psswd, $db_l2jdb, $dblog_location, $dblog_user, $dblog_psswd, $dblog_l2jdb, $guest_allow, $all_users_maps, $all_users_recipe, $register_allow);

// Print top of page
echo "
			<p class=\"dropmain\">&nbsp;</p>
			<center>
	<table width=\"80%\" cellpadding=\"20\" class=\"dropmain\">
	<tr>
	<td class=\"dropmain\">
			<h2 class=\"dropmainblack\"><center>Welcome to ...</center></h2>


	<center><img src=\"" . $images_dir . "l2-1.jpg\" alt=\"\" border=\"0\" height=\"480\" width=\"600\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">THE GAME</strong></p>
	 <p class=\"left\">In the begining, dungeons were text driven adventure games.  \"Go North\" was the staple command, and there was always a dark place where you needed a lamp turned on before the computer would describe the room to you.  That was the 1980's.  Today, however, the world of Dungeons and Dragons and adventuring has been brought kicking and screaming in to full 3D live action.  The turn based systems and endless dice throwing of games played by people huddled around a table and a game book, are now played simultaniously by thousands of players across the world.</p>
	 <p class=\"left\">This is a world where you can become other characters and have adventures either on your own, or with other people. You can do battle with game monsters, talk and trade with the various automated non-player characters, or even better, join forces with other real players like yourself, and engage in some of the more difficult aspects of the game. You can see your character and watch the battles as they happen. It is almost possible to feel the land beneath your feet as your character walks among strange creatures on an unfamiliar world. Don't believe me? Try it for yourself!</p>
	<p class=\"left\">This guide describes some of the basic rules of the game and how to get around. I hope to give people the tips to get the most out of the game without spoiling it too much. It aims to get you going and show you the paths you can take. So here, then, are the basics of the game.</p>
	<p class=\"left\">Moving around the area is done by mouse. With the cursor in the game window, holding down the right mouse button and moving the mouse will adjust the camera viewpoint. Pressing the Page Up and Page Down keys will zoom your view in or out. Sometimes things will get in the way and the camera will move in, to try and make sure that you can see your character at all times. It does get annoying on occasion, but such is life.</p>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td> <p class=\"left\"><img src=\"" . $images_dir . "l2-2.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"110\" width=\"230\">This is your basic status meter. You'll find it at the top left of the screen originally, but like most things in the game you can move it. Personally, I have found little reason to move any of the status boxes that appear, but this is up to you.</p>
	<p class=\"left\"><strong>CP</strong> are your combat points. This is only used in player versus player (PvP) and as you take hits, your CP will start to go down. When it reaches 0, then your HP will start to go down, as normal.</p>
	<p class=\"left\"><strong>HP</strong> is your health meter. If you Hit Points reach 0, then you're dead. When you are hit, it will take points from this meter. The HP will regenerate over time, (even when you are in a fight) and this regeneration can be speeded up by sitting down somewhere safe.</p> 
	<p class=\"left\"><strong>MP</strong> are Magic Points and are used whenever you perform certain magic tasks or skills that need them. Like HP, they regenerate by themselves over time.</p>
	<p class=\"left\"><strong>XP</strong> stands for eXperience Points, and that is what the silver bar notes. As you gain experience, your character goes up in levels. When the silver bar reaches 100%, then you, \"Level Up,\" and the bar returns to 0%. In this example, the character Kirana, is level 23 and is 32.4% on the way to the next level.</p>
	<p class=\"left\">The higher the level of your character, the better and stronger the equipment and armor you can use and wear.  More on that later.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td> <p class=\"left\"><img src=\"" . $images_dir . "l2-3.jpg\" alt=\"\" align=\"left\" border=\"0\" height=\"340\" width=\"350\">This is your message window.  Whenever something happens of any note, it shows up in this window.</p>
	<p class=\"left\">You will note that different types of messages are different colours. You will soon learn to differentiate the colours and be on the lookout for the different types of events.</p>
	<p class=\"left\">Note the bottom of the screen that there are a number of tabs. This controls the, \"chat.\" If you type anything on the keyboard that Lineage 2 doesn't recognise as a command, it will be put in the chat line. When you then press RETURN, the chat you have typed goes in to the game.</p>
	<p class=\"left\">Who can hear you depends on how you start your message. If you don't precede the chat, then everyone in a certain vicinity can hear you, just like in real life. You can talk to an invidividual, however, by typing a double quote, followed by their name ... eg. <strong>\"Gordon I'm going in to attack!</strong> would have then appeared on Gordons message window, (in purple!) no matter where he was in the game. Note that you don't have to finish the quotes like you would do in English, and also on pressing the quotes, the game will automatically fill in the name of the last player who you talked to, or of who talked to you. This way of doing things works well for 90% of the time, but there is the odd occasion where it makes life difficult. Talking to another player directly is also known as whispering.</p>
	<p class=\"left\">Keep an eye on your message window, as you never know if anyone is trying to talk with you. There is a smaller message window above the first, and this is usefull if you are in a town where there is a lot of talking going on, as this smaller window doesn't actually show the conversations; only the important system messages.</p>
	<p class=\"left\">Other precedences are \"!\" to shout to a larger radius (don't use unless you have to; GM's are the only ones who can shout to all players regardless of location) and also \"@\" which allows you to talk to everyone in your, \"clan,\" if you join one. Should you join others in a party, then \"#\" will send the message to everyone who is in your current party.</p>
	<p class=\"left\">Precede the text with a \"/gm \" to send a message to any logged in GM's (Game Monitors) but on some servers this doesn't work, so it is best to whisper to a GM if you really need some help.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td> <p class=\"left\"><img src=\"" . $images_dir . "l2-4.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"382\" width=\"331\">The map shows you where you are. The shortcut key to bring it up and stow it away again is ALT + M. There isn't actually much to the map (or at least, not much that I have used!)</p>
	<p class=\"left\">The arrow in the centre shows you where you are (you are the center of the arrow) and it points in the direction where your, \"camera,\" is looking. This isn't the direction that your character is looking, but where you, yourself are looking in your third player perspective.</p>
	<p class=\"left\">If you put your mouse over the map and hold down your left mouse button, you'll find that you can drag the map around so that you can venture around it. You can not use the map, however, for giving directions like you can in other games. ie. you can't click on a point on the map and expect your character to go there; it won't work.</p>
	<p class=\"left\">On some servers, the map has to be obtained before it can be used, and to get it, you have to complete a quest.  The quest is usually located in the starter towns.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td> <p class=\"left\"><img src=\"" . $images_dir . "l2-5.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"504\" width=\"46\">The last word on your basic screen display is the quick bar. You can drag prety much anything in here, so that it can be used quickly. You will note that the numbers down the side, relate to your F keys on the keyboard. Obviously, the things you put in here will vary from character to character, but I'll explain the few I have here...</p>
	<p class=\"left\">The first three are from the, \"actions,\" menu. The top one is attack, the second is target next closest enemy and the third is to sit.</p>
	<p class=\"left\">The second two are skills, or possibly spells, and these use some of the MP ability. One is power strike, which gives me a better chance to do more damage when I make a strike. However, once used, it takes a while to recharge so I can not use it on every strike I make. When it recharges, the icon goes dark, and a sweeping hand of colour comes back in to it like the hand of a clock as it recharges again.</p>
	<p class=\"left\">The lower two are from my items. The sword is one of my weapons. If I have two weapons, I can put them both in here, and it allows me to swap easily between them.</p>
	<p class=\"left\">Soulshot is the lower icon, and it is important. This ability greatly enhances the damage you do when you make a strike. You have to right click it to activate, or de-activate it. If it is active, it will shimmer a little. If you are in doubt as to whether is it active or not, just right click it and see what the message window says about its status.</p>
	<p class=\"left\">You will notice, on the top of the bar, the little arrows and the number. You can keep multiple copies of this bar, and have different skills, actions or items in each one depending on what circumstances you are in. When you are in town, for example, you will probably want talking and trading actions ready to hand.</p>
	<p class=\"left\">Also, while here, a quick note about, \"buffs.\" Buffs are active skills, which you must select to use. Rather than have a direct effect like an attack, however, they alter the characters attributes for a while, or they can even be used to buff another characters abilities. The range of buffs and their effects are quite wide and differ from one race and career path, to another. They are obtained like any other skill and can also be placed in the side bar for use. A buff typically has a time limit associated with it, and it can be seen in the top left of the screen. Hovering the mouse over a buff will tell you what it is, what it does, and how much time it has left to run.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	<p class=\"dropmain\"><strong class=\"dropmain\">THE CHARACTERS</strong></p>
	<p class=\"left\"><img src=\"" . $images_dir . "l2-8.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"400\" width=\"255\">In the game, you can choose from a number of different races. Each has their own strengths and weaknesses, but I will leave that to your own research. I will tell you, however, that the dwarf is an important character. It is the only character which can become very good at, \"crafting,\" items from recipies that you find, or you can train a dwarf to be a, \"spoiler,\" who will be able to get items from creatures that normal fighters, rangers and mages can't get.</p>
	<p class=\"left\">The basics of the game is to run around killing the creatures. When you kill a creature, a number of things happen ... Firstly you get some experience points (XP) for the fight, and some skill points (SP). You can also get some Adena (money) and the enemy can naturally drop an item or two. Which items the creatures drop depends greatly on the type of creature it is. A dwarf can go one further by using, \"spoil,\" techniques. This is a way of getting further items out of the creature by way of magic.</p>
	<p class=\"left\">The XP points increase your level, as seen before. The SP points are exchanged for training in various skills that are available to you. Some of these skills include improving your skill with a weapon (and increasing your ability to hit them!) and also healing faster when you are sat down. The Adena are used to buy equipment, magic charms, armor and other things within the game.</p>	
	<p class=\"left\">A dwarf crafter can use recipies to make a range of things that you otherwise wouldn't be able to get in the shops. It does typically need another character to get some of the ingredients, though. I'll take you through making some D grade soulshot later.</p>
	<p class=\"left\">You can now start to see how you will need to maintain a number of characters of different races and abilities, or else you will have to do a lot of trading with other people.</p>
	<p class=\"left\">If all that wasn't enough, then the characters can progress their skills and follow various career paths; I aluded to this in that a dwarf can become a crafter or a spoiler. The character has to progress through various quests to follow their chosen career path, but although the quests do become available on reaching the next, \"grade,\" there is nothing forcing the player to follow their career path; however better skills do not become available unless the character is progressed further.</p>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">LEVELING UP</strong></p>
	 <p class=\"left\">Now that you have got the idea of gaining experience and progressing to different levels, there is another structure called the, \"grade.\" Level 0 to 19 is not graded; level 20 to 39 is grade D; level 40 to 59 is grade C, and further. The point of this is to prevent progress too quickly. Certain types of armor, weaponary and magical items are graded. If a class D player were to try and use an item meant for a grade C character, then the game would heavily penalise the character for trying to do so. The game is all about steady, honest progress.</p>
	 <p class=\"left\">Some kinds of support items (like soulshot, for example) are also graded. I had soulshot of class D, but because I was using a no grade weapon, it wouldn't work. I also had a spell to enchant D grade armor, but because I didn't have any D grade armor, the spell wouldn't work.</p>
	 <p class=\"left\">As your character increases, however, you will find that creatures who are a few levels below you, will stop dropping things and will no longer give you experience points for the kill. This is so that the player is forced to venture in to the game, rather than just pick on the easy targets. You will also notice that as you progress in levels, the next level up requires more XP to attain.</p>
	 <p class=\"left\">Generally, when you target an enemy, a box appears at the top centre of the screen with the enemies current HP. You will see their HP decrease during the fight. The enemies name, however, will also be a different colour depending on the level difference between you and it. Red means you're taking on someone out of your league, down through yellow and white, to navy blue, where the character isn't likely to drop anything for you.</p>
	 <p class=\"left\">After a couple of hours of playing, it is generally possible to achieve level ten and get a good feel for the game, before starting to get stuck in to the meatier parts of the game and start to put some effort in to adventuring and levelling.</p>
	 <p class=\"left\">When buying or making armor, there can sometimes be additional bonuses for wearing armor of a complete set, so chose your weapons and armor carefully when you cross grades.</p>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td>
	 <p class=\"dropmain\"><strong class=\"dropmain\">TRANSFERING AND STORING ITEMS</strong></p>
	 <p class=\"left\">As your character has a limit to the amount of weight they can carry, you can go to a warehouse and store items there. You can call in to any warehouse you like and retrieve the items at a later date. The basic warehouse and transfer rules are as follows...</p>
	 <p class=\"left\"><strong>Personal Warehouse</strong> can be accessed from any warehouse in the game. You can put an item in to your personal warehouse in one town, and extract it in another. It does cost to deposit items in the warehouse, but not to withdraw them.</p>
	 <p class=\"left\"><strong>Freight</strong> is the way to transfer items between two of your characters. Operates just like the persoanl warehouse, with the exception that the character has to pick up the freight from the same warehouse in which it was deposited.</p>
	 <p class=\"left\"><strong>Clan Warehouses</strong> are the same as personal warehouses, but are accessable by all clan members.</p>
	 <p class=\"left\">Not every warehouse member can handle freight, by the way. Normally, there should be one warehouse staff who can handle freight, though, just try them in turn.</p>
	 <p class=\"left\">Also note that the behaviour of freight can be changed on the server, so if you are having problems, check with a GM as to the server specific rules.</p>
	 <p class=\"left\">In order to join a clan, a member of the clan must invite the other character to join. That means both characters have to be on line at the same time. If you can only have one account on-line at the time, then using the clan warehouse as a freight-type option without the location restriction, is much harder to pull off as you would need both your characters to be on line at the same time.</p>
	 <p class=\"left\">I wasted an awful lot of Adena in transport fees finding all this out.</p>
	 <p class=\"left\">Trades can be initiated between two people in order to pass items between them. Dropping items on the floor for another character to pick them up is not recommended, as some game bugs have seen the items stuck to the floor and thus lost, as no one can pick them up again.</p>
	 <p class=\"left\"><img src=\"" . $images_dir . "l2-6.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"401\" width=\"257\">This is a look at the inventory window. It controls items that you are wearing in the top section, and in the middle section you can see items that your character is currently carrying.</p>
	 <p class=\"left\">Note the, \"quest,\" tab. This will show you the current quest items that you are carrying. It is also useful as a reminder to where you are in some quests, as well as looking at the quest window itself.</p>
	 <p class=\"left\">In the wearing part, you can see sections for the various items you can wear. Two rings, two earings and a necklace are the more usual fare. These are usually items used for defence against magic spells cast by enemies. To the left you can see the more usual slots for helmet, armor, shoes, gloves and weapon/shield. You can drag items from the list in the middle, in to these slots. Remember that enabling an item that is above your characters grade will handicap your character.</p>
	 <p class=\"left\">You can also drag items from here in to the quick bar on the right, so that you can access them by pressing the F keys. Remember that this can work for a variety of items, including weapons (for quick change) and spells such as soulshot and spiritshot.</p>
	 <p class=\"left\">At the bottom of the window is the amount of Adena (money) you are carrying, (you can also store money in a warehouse, trade it to someone or freight it to another character) and also your current weight status. As your character progresses, it is possible to carry more weight, but the average is 50% of your capability. Anything over this, and you are burdening yourself. 100% weight and you will hardly be able to move. Don't do what I did, which is to stock up with 10,000 soul shot and wonder why you can't walk. Some servers report that soulshot carries no weight, but on most, it does.</p>
	</td></tr></tbody></table>
	<table><tbody><tr><td>
	 <p class=\"left\"><img src=\"" . $images_dir . "l2-7.jpg\" alt=\"\" align=\"left\" border=\"0\" height=\"172\" width=\"276\">This shows you what happens when a character is carrying too much weight, or some other bonus/handicap is applied beyond the normal play. Hovering the mouse over the icon will give you an explanation of what the penalty is, and why you've got it. In this case, because I'm carrying too much, my rate of recovery is slowed down.</p> 
	 <p class=\"left\">The image above shows the figures that are displayed if you hover the mouse over the weight bar. The figure on the right is your 100% maximum, and the figure on the left is your current burden. Everything you carry, including armor, etc. will have a weight associated. Sometimes, magical items are available to help with the weight issue. As you level up, your natural ability to carry more also increases, so you will be able to wear heavier, more powerful armor as you progress.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong>LOOKING FOR ITEMS AND MONSTERS</strong></p>
	 <p class=\"left\">If you need to look for a particular item or monster, (usually refered to as Mobs) then don't count on the Internet. Many servers have their mobs in different places, etc. Use the, \"Drop Calculator,\" that is geared for the server you are playing on. Some servers which are run for free, do charge a small fee for using their drop calc services. You can not even count on a specific monster dropping or sweeping particular items, either, as these are also changed by the server operators. Also note that some mobs are underground, so if you can't find them on the surface, look for an entrance that will take you in to the dark depths!</p>
	 <p class=\"left\">If you do search for a character on a drop calc, (as they display maps with marks to show where the monsters are) then be aware that if you don't find them, they might be underground. You might have to search for an entrance to an underground area. Dwarves will find mines early on in their game.</p>
	 <p class=\"left\">Also, on later servers, some mobs only spawn during the day or the night.  Also, in some cases, the game has a set number of locations (say, 10) and a number of mobs to spawn for them (say 2) so in this example, for the ten locations given, there will only be mobs at two of them, and only the server decides this at start up time.</p>
	<center><hr width=\"80%\"></center>
	<table><tbody><tr><td>
	 <p class=\"dropmain\"><strong class=\"dropmain\">FIGHTING MONSTERS</strong></p>
	 <p class=\"left\"><img src=\"" . $images_dir . "l2-9.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"459\" width=\"281\">When you look at a monster look for the level number on top of the name; something like Lv12. If there is an asterisk after it, like Lv12* then the creature is agresive and if you come to close to it, it will attack you. Otherwise the creature will wait for you to attack it. In the pictures, the Premo Prime is agressive, and would come for me if I got too close. The Titan's Creation, Bemos, would only come for me if I attacked it first, or attacked another of its kind in close proximity to it.</p>
	 <p class=\"left\">Be aware that not all servers will show this number, so you will have to rely on the drop calc, or your intuition, as to whether or not you get in a fight with it.  Again, if there is a drop calc available, it should give you the information you need to determine the level and agro of a mob.</p>
	 <p class=\"left\">If you attack a creature, and there is another of its bretheren close by, whether active or passive, the other creature can come to the assistance of its felow and you can find yourself under simultanious attack.</p>
	 <p class=\"left\">You can outrun most mobs if you get in to too deep a pickle. Keep running and eventually they will give up the chase. Rather run than death. Rules on death also vary from server to server; sometimes you have to return to the spot of your death to pick up dropped items. Don't leave it too late to run if you have to, as some mobs cast spells that can cover a little distance.</p>
	 <p class=\"left\">Some of your magic defences and attacks are more effective on some monsters than others. Experience will tell you which work, and which don't, although chance does play a part. Rewards in terms of experience and skill points, as well as drop and sweep chances, are also variable from one server to another.</p>
	 <p class=\"left\">Don't expect the normal rules of physics to apply. I've found an Orc Archer underwater, and I've also been chased half way across an island by a shark!</p>
	 <p class=\"left\">By chatting with people, you can become part of a party, or clan, and take part in group raids and activities that you otherwise wouldn't be able to undergo alone. If you become part of a party, then be aware of the party settings in the options menu, as this governs how spoils, drops and experience points are distributed among party members. Most people I have played with prefer working in clans as they help each other level up, and by the time they get involved in the serious action, no one is too bothered about who gets the kills.</p>
	 <p class=\"left\">By looking for a non-player character (NPC) with a big yellow exclamation mark above their head, you can generally pick up a quest from them. This involves killing some kind of creature or other for a reward. These vary greatly. Sometimes, however, the NPC will be lying and won't actually have a quest, and other times you can find quests with characters that are not advertising them.</p>
	 <p class=\"left\">The positioning of some of the creatures for quests, assuming you are not playing on an official server, may have been moved by the administrators, for strategic reasons. If you scour an area and can't find the mob in question, don't waste hours scouring the area, but get in touch with a GM who should be able to put you straight.</p>
	 <p class=\"left\">On top of all this are further mass scripted quests, for which general anouncements will be made, but I'll cover that when I understand more about it myself. If you want to know about these, it is likely you will need to be a high level character, and will porbably have struck up some friendships in the game, so if I haven't covered the subject yet, ask someone in game. They will likely have more of an idea of the server specific quests anyway.</p>
	 <p class=\"left\">There are some dungeons (or areas) in the game which can only be conquered by going in mob handed. If the administrators have set up an area of large numbers of agressive mobs, then you'd get slaghtered if you went in there alone. It would take good numbers of players to get in to this kind of area and survive.</p>
	 <p class=\"left\"><strong>REMEMBER - </strong>that creatures respawn in a short period of time. If you've just had a battle with an agressive character, then move away from the area before you sit down for a rest, otherwise the mob will respawn and start attacking you before you have had a chance to recover.</p>
	 <p class=\"left\">There are also Bosses and Raid Bosses around. These are seriously kick ass beasts which you don't stand a chance of taking on alone. Although their charcter level might look to be within range, they have serious powers and can absorb loads of damage. These characters can typically be spotted as they are sometimes larger than life, and have an entorauge. If you're reading the drop calculator, then a mob which only has one spawn pouint in the game is usually a boss or raid boss. This is done, as these mobs are geared up to take being hit by a party and the rewards for parties taking them are usually sweet, like multiple piece of high grade armor and similar. If you are seeking an item that is dropped or spoiled by one of these bosses, then your best best is to look for a recipie, 'cause you ain't going to take them alone!</p>
	 <p class=\"left\">Some mobs are in restricted areas, like the Necropolis' as this is down to another part of the games team play element called the Seven Signs. More on that later when I experience it and add it.</p> 
	 <p class=\"left\">You can also siege castles as a clan, and can thus take a castle for your clan. There are also clan halls within the game so that people of particular clans can get together with a little privacy. Generally, if you're a member of a clan and you get killed, if the clan has a castle or hall, you'll see these options pop up as respawn points. I'll post more on the basic rules of castle taking when I experience it myself!</p> 
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">USING RECIPIES</strong></p>
	 <p class=\"left\"><img src=\"" . $images_dir . "l2-13.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"402\" width=\"256\">This example assumes a dwarf that has completed the level D challenges.</p>
	 <p class=\"left\">Soul Shot D is a useful thing to have around.  A grade D Dwarf can make this.</p>
	 <p class=\"left\">The recipie must first be obtained from a mob and the dwarf must learn it by reading it from the inventory. A recipie need only be read once, but the dwarf needs to be of a level to be able to read it in the first place.</p>
	 <p class=\"left\">In the skills tab of the character status/actions menu, click on the appropriate skill to open up the recipie book. This is another window which will list the spells your character has read and knows. This list can get quite lengthy in the long run, so try and only read recipies that you will really use.</p>	 
	<p class=\"left\">Obtain the, \"crystalisation skill,\" by achieving sufficient skill points and training with a blacksmith, and then buy some, \"soul ore,\" from a shop and, \"excellence leather gloves,\" from an armory. Learning the chrystalise skill will add another button in to your inventory list, just to the left of the adena and weight bars. The gloves are chrystalised by opening your inventory list and dragging the gloves on to the crystalisation icon at the bottom of the inventory list. This then generates D grade crystal which is automatically put in to your inventory. (You can actually crystalise leather boots and other leather items as well - experiment!)</p>
	 <p class=\"left\">The soul ore and the D grade crystal are the raw ingredients required for the creation of the D grade soul shot. Once you open your recipie book, click on the recipie to open it and you will then see a window reporting the number and type of items you need to make the recipie, along with how many you have actually got in your current inventory. Note that you need to be carrying the items; it will not automatically get them from any warehouse. You can then click on the create button to make the item, and the necessary adjustments will be made to your inventory.</p>
	<p class=\"left\">Not all recipies are 100% sucesses, however. Sometimes they will fail depending on the throw of a dice. The recipie should say what the chance of success is.</p>
	 <p class=\"left\">Note that if you want to go in to the depths of the recipie system, it is even possible for the dwarf to create the excellence leather gloves from other ingredients if you have the recipie and want to save more adena.</p> 
	 <p class=\"left\">Once the soul shot has been created, the dwarf can then use the soul shot itself, or transfer it to another character for their use, or they can even sell it to other players and make a profit by setting up a stall.</p>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">MACROS</strong></p>
	<table><tbody><tr><td>
	 <p class=\"left\"><img src=\"" . $images_dir . "macro.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"409\" width=\"560\">Macros are very handy tools and can help you out of all sorts of spots. Basically, everything you click on is actually sending a typed command to the program. The icons are already macros. Try issuing the commands /sit and /stand at the console. Note that your character sits and stands, just like pressing on the icon ... well, almost!</p>
	 <p class=\"left\">A macro (in case you're not sure) is a string of pre-typed commands. You hit the button, and the macro, \"runs,\" executing those commands one after the other, just as if you had typed them one after the other at the keyboard.</p>
	 <p class=\"left\">To start with, I'm going to teach you a wonderfully useful macro that was taught to me by the wonderful Jane Muffin. If you have ever come across a mob that you can't attack because the system just won't let you, then you need /attack force - yes typing this in at the keyboard will do the job, but on most servers you may need to do it more regularly. First off, access the Macro section by pressing ALT + R together. The Macro window will pop up. Click the Add button and you will now get the macro edit window. Give, \"Attack Force\" as the name, \"atkf\" as the acronym (you've only got four letters) and in the 00 box, type, \"/attack force\" and click save. Congratulations, you've now made your first macro.</p>
	 <p class=\"left\">Now you can see that green button on it with the four letters that is your acronym. You can actually drag that button, just like everything else, in to your side bar. Many people overwrite the default attack button with this macro, as it is so useful. When you're done, you can just close the macro window.</p>
	 <p class=\"left\">Another of Janes useful tips is to put all your buffs in a macro. That way, you just have one macro button in your side bar, and it triggers all your buffs automatically!</p>
	 <p class=\"left\">Like before, press ALT R to get the macro window up, and press New to create a new macro. While that window is open, now also open your skills window. You can drag and drop your skills in to the 00, 01, 02, etc. slots on the macro editor! Note that the commands themselves actually appear in the macro editor. Once you've put all your buffs in here, you can just give the macro a name and an acronym, then you can save it. Finally, you can drag the macro button in to your sidebar and use it to fire off all your buffs. You can also do this with the buffs that you use on other characters. It saves a lot of time.</p>
	 <p class=\"left\">One final word about using macros for things like buffs, is that even if you click on something else, the macro will stop running, so be sure to stay still throughout the macros execution.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">PETS</strong></p>
	<table><tbody><tr><td>
	 <p class=\"left\"><img src=\"" . $images_dir . "pet1.jpg\" alt=\"\" align=\"right\" border=\"0\" height=\"353\" width=\"469\">A pet is quite a drain on your resources, but good fun to raise. My experience is based on the hatchling. (and thanks to Nic for the advice!)</p>
	 <p class=\"left\">If you think that the quest for a hatchling is a pain in the rear end, then check out what you have to do level the pet once you've got it. Firstly, you need equipment. Without equipment, you're newbie pet won't be able to kill a level 1 Imp, let alone anything larger. Check out the pet shop, and the most expensive hatchling equipment will set you back two milion adena for a start. Then you have to buy food for the beast.</p>
	<p class=\"left\">You can't unsumon a pet that is hungry, so always make sure you've got enough to satisfy its stomach before you send it back, otherwise you've got a hungry pet on your hands which won't leave your side until its belly is full; and unlike your character, the pet is always becoming more hungry by the minute. Generally, somewhere around 50% fed will enable you to unsummon your pet away again. I haven't yet let my pet go hungry, but I guess that it probably dies.</p>
	 <p class=\"left\">To feed your pet, drag some pet foot in to the pets inventory, (on the server I play on, about 40 units is usually enough to go from 30% fed to 80% fed) and then double click on it in the pet inventory to have the little terror eat it.</p>
	 <p class=\"left\">Levelling up your pet is done in battle. You attack a mob, and instruct your pet to attack it also. The mob will attack the one doing it the most damage (you) so your pet will get away unscathed. Pick a mob that is around your level, and don't use soulshot. If you do more damage than your pet does, then your pet will get a lower share of the XP and won't level as fast. However, be ready to click on your shoulshot if the battle doesn't seem to be going your way.</p>
	 <p class=\"left\">My trick is to find a suitable group of mobs (when I was level 36 I picked the small group of Wyverns, Basilisks and Road Scavengers that are between the South end of Death Pass and Giran Town) and I would start hacking in to them, one by one. When I juded that I was getting in to dangerous HP teritory (after about four or five fights depending on the strength of my armor and weapon) I'd feed my pet and unsummon it. Then I could sit down and rest without my pet getting hungrier, and then resummon it when I was ready to go again. Be warned not to risk dying, as I'm not sure what state that will leave your pet in ... probably dead, so be ready to have some form of ability to resurect it in case this happens.)</p>
	 <p class=\"left\">Another note is that every time you summon a pet, you need to transfer their  mour and weapon in to their inventory, and enable them. Armed items in your pets inventory are seen surrounded by green.</p>
	 <p class=\"left\">If your pet has died and you need to target it in order to resurect it, try using the /target command, eg. <strong>/target cuttie pie</strong> - and then use the resurect scroll.</p>
	</td></tr></tbody></table>
	<center><hr width=\"80%\"></center>
	 <p class=\"dropmain\"><strong class=\"dropmain\">STRATEGIES</strong></p>
	<ul>
	<li> <p class=\"left\">If running two dwarves, use ones warehouse for storing items and the other for storing armor that isn't in use. Keeping the two separate helps when the warehouses start to seriously get full!</p></li>
	<li> <p class=\"left\">Keeping the good armor helps as hand-me-downs for your next characters. Saves an awful load of time and money, because selling things back to the shops never gets you the same price again.</p></li>
	<li> <p class=\"left\">To level up on your own, grab four or five thousand soulshot for your weapon and go out and find a series of mobs of around your level (or one or two levels higher) and when you find a group of them, you can go around the group. By the time you've killed the last one and had a sit down, then the first one has respawned and you're ready to go again.</p></li>
	<li> <p class=\"left\">Characters can't walk over things, but there is a bug ... take your zoom out to maximum, and change your view to overhead. This way, your character can sometimes struggle against a small lip, and win! I've even crossed a mountain range like this.</p></li>
	<li> <p class=\"left\">Read everything that goes on. Frequently bits and pieces of games change from server to server, so some Internet instructions and guides aren't always accurate. If you get in to trouble, or get stuck, remember that /gm will talk to any GM that is on line at the time. Also check out their forums and resources for issues that others have come across before you.</p></li>
	<li> <p class=\"left\">Your grade is directly related to your character level. Your skill, however, isn't. You have to complete quests at various points in order to achieve access to different and higher level skill sets.</p></li>
	<li> <p class=\"left\">This may sound obvious, but the quicker you can dispatch your enemies, the shorter the fight and the less damage you end up taking, so make your weapon your focus over your armor. Also try and draw off one enemy at a time so that you're not swamped with attackers, because they can take you out more quickly. Also, the quicker you take out an enemy, the less soulshot you use!</p></li>
	<li> <p class=\"left\">If you are getting Pk'd (Player Killed) by other players too much, it is probably time to move server.  Don't be fooled by someone wanting to fight who seems to be in low armor; they could have friends around the corner, or powerful armor and weapons on their quick bar that can be engaged in a second, after you have struck your first blow, gained karma yourself and commited to the fight.  It is up to you if you want to get karma problems, as players with bad karma get attacked by the town guards.</p></li>
	<li> <p class=\"left\">There are also a lot of beggers on many servers, some of whom start to hit you if you don't give them adena.  Talk with a GM about them, and if you can take a screen shot of the chat, then you have the proof to back you up.  It isn't all a world of sweetness and light!</p></li>
	</ul>
	<h2 class=\"dropmainblack\"><center>Are you ready to join the action?</center></h2>
		<center><img src=\"" . $images_dir . "l2-10.jpg\" alt=\"\" border=\"0\" height=\"648\" width=\"745\"></center>
		 <p class=\"dropmain\"></p>
		<center><img src=\"" . $images_dir . "l2-12.jpg\" alt=\"\" border=\"0\" height=\"600\" width=\"745\"></center>
		 <p class=\"dropmain\"></p>
		<center><img src=\"" . $images_dir . "l2-11.jpg\" alt=\"\" border=\"0\" height=\"665\" width=\"745\"></center>
		<p class=\"dropmain\"></p>
		<center><img src=\"" . $images_dir . "l2-14.jpg\" alt=\"\" border=\"0\" height=\"757\" width=\"745\"></center>
		<p class=\"dropmain\"></p>
		<center><img src=\"" . $images_dir . "l2-15.jpg\" alt=\"\" border=\"0\" height=\"663\" width=\"745\"></center>
		
	</td>
	</tr>
	</table></center>
	";

wrap_end_dummy($username, $token, $_GET, $_POST, $langval, $language_array, $top_ten, $db_location, $db_user, $db_psswd, $db_l2jdb, $dblog_location, $dblog_user, $dblog_psswd, $dblog_l2jdb, $sec_inc_gmlevel, $sec_inc_admin, $refresh_timer, $refresh_string, $quality_level);

?>
