
drop table knightetcitem;
CREATE TABLE `knightetcitem` (
  `item_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '',
  `icon` varchar(50) NOT NULL DEFAULT '0',
  `crystallizable` enum('true','false') NOT NULL DEFAULT 'false',
  `weight` smallint(4) NOT NULL DEFAULT '0',
  `consume_type` varchar(9) NOT NULL DEFAULT 'normal',
  `material` varchar(11) NOT NULL DEFAULT 'wood',
  `crystal_type` varchar(4) NOT NULL DEFAULT 'none',
  `duration` mediumint(5) NOT NULL DEFAULT '-1',
  `time` mediumint(5) NOT NULL DEFAULT '-1',
  `price` int(10) unsigned NOT NULL DEFAULT '0',
  `crystal_count` smallint(4) unsigned NOT NULL DEFAULT '0',
  `sellable` enum('true','false') NOT NULL DEFAULT 'false',
  `dropable` enum('true','false') NOT NULL DEFAULT 'false',
  `destroyable` enum('true','false') NOT NULL DEFAULT 'false',
  `tradeable` enum('true','false') NOT NULL DEFAULT 'false',
  `depositable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_stackable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_questitem` enum('true','false') NOT NULL DEFAULT 'false',
  `skill` varchar(70) NOT NULL DEFAULT '0-0;',
  PRIMARY KEY (`item_id`));

drop table knightweapon;
CREATE TABLE `knightweapon` (
  `item_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` varchar(120) NOT NULL DEFAULT '0',
  `icon` varchar(50) NOT NULL DEFAULT '0',
  `bodypart` varchar(15) NOT NULL DEFAULT 'none',
  `crystallizable` enum('true','false') NOT NULL DEFAULT 'false',
  `weight` smallint(4) NOT NULL DEFAULT '0',
  `soulshots` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `spiritshots` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `material` varchar(11) NOT NULL DEFAULT 'wood',
  `crystal_type` varchar(4) NOT NULL DEFAULT 'none',
  `p_dam` smallint(4) NOT NULL DEFAULT '0',
  `rnd_dam` smallint(3) NOT NULL DEFAULT '0',
  `weaponType` varchar(20) NOT NULL DEFAULT 'none',
  `critical` smallint(3) NOT NULL DEFAULT '0',
  `hit_modify` tinyint(2) NOT NULL DEFAULT '0',
  `avoid_modify` tinyint(2) NOT NULL DEFAULT '0',
  `shield_def` smallint(4) NOT NULL DEFAULT '0',
  `shield_def_rate` smallint(3) NOT NULL DEFAULT '0',
  `atk_speed` smallint(4) NOT NULL DEFAULT '0',
  `mp_consume` tinyint(1) NOT NULL DEFAULT '0',
  `m_dam` smallint(4) NOT NULL DEFAULT '0',
  `duration` mediumint(5) NOT NULL DEFAULT '-1',
  `time` mediumint(5) NOT NULL DEFAULT '-1',
  `price` int(10) unsigned NOT NULL DEFAULT '0',
  `crystal_count` smallint(4) unsigned NOT NULL DEFAULT '0',
  `sellable` enum('true','false') NOT NULL DEFAULT 'false',
  `dropable` enum('true','false') NOT NULL DEFAULT 'false',
  `destroyable` enum('true','false') NOT NULL DEFAULT 'false',
  `tradeable` enum('true','false') NOT NULL DEFAULT 'false',
  `depositable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_stackable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_questitem` enum('true','false') NOT NULL DEFAULT 'false',
  `change_weaponId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `skill` varchar(70) NOT NULL DEFAULT '0-0;',
  PRIMARY KEY (`item_id`));

drop table knightarmour;
CREATE TABLE `knightarmour` (
  `item_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `name` varchar(120) NOT NULL DEFAULT '',
  `icon` varchar(50) NOT NULL DEFAULT '0',
  `bodypart` varchar(15) NOT NULL DEFAULT 'none',
  `crystallizable` enum('true','false') NOT NULL DEFAULT 'false',
  `armor_type` varchar(5) NOT NULL DEFAULT 'none',
  `weight` smallint(4) NOT NULL DEFAULT '0',
  `material` varchar(15) NOT NULL DEFAULT 'wood',
  `crystal_type` varchar(4) NOT NULL DEFAULT 'none',
  `avoid_modify` tinyint(2) NOT NULL DEFAULT '0',
  `duration` mediumint(5) NOT NULL DEFAULT '-1',
  `time` mediumint(5) NOT NULL DEFAULT '-1',
  `p_def` smallint(3) NOT NULL DEFAULT '0',
  `m_def` smallint(3) NOT NULL DEFAULT '0',
  `mp_bonus` smallint(3) NOT NULL DEFAULT '0',
  `price` int(10) unsigned NOT NULL DEFAULT '0',
  `crystal_count` smallint(4) unsigned NOT NULL DEFAULT '0',
  `sellable` enum('true','false') NOT NULL DEFAULT 'false',
  `dropable` enum('true','false') NOT NULL DEFAULT 'false',
  `destroyable` enum('true','false') NOT NULL DEFAULT 'false',
  `tradeable` enum('true','false') NOT NULL DEFAULT 'false',
  `depositable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_stackable` enum('true','false') NOT NULL DEFAULT 'false',
  `is_questitem` enum('true','false') NOT NULL DEFAULT 'false',
  `skill` varchar(70) DEFAULT '0-0;',
  PRIMARY KEY (`item_id`));



